@baseUrl = http://localhost:8080
@userId = 1
@questionnaireId = 1
@choiceId = 1
@parentCommentId = 1
@seedUserId = 1001
@seedQuestionnaireId = 2001
@seedFollowingUserId = 1002
@seedCommentId = 6003

### Delete questionnaire like
DELETE {{baseUrl}}/v1/questionnaires/{{seedQuestionnaireId}}/likes/{{seedUserId}}

### Delete questionnaire
DELETE {{baseUrl}}/v1/users/{{seedUserId}}/questionnaires/{{seedQuestionnaireId}}

### Delete follow
DELETE {{baseUrl}}/v1/users/{{seedUserId}}/follows/{{seedFollowingUserId}}

### Delete comment
DELETE {{baseUrl}}/v1/users/{{seedUserId}}/comments/{{seedCommentId}}
