@baseUrl = http://localhost:8080
@seedUserId = 1001
@draftQuestionnaireId = 2004

### Patch user profile
PATCH {{baseUrl}}/v1/users/{{seedUserId}}
Content-Type: application/json
Accept: application/json

{
  "display_name": "更新後のタロウ",
  "bio": "GoとMySQLを勉強しています"
}

### Patch user setting
PATCH {{baseUrl}}/v1/users/{{seedUserId}}/setting
Content-Type: application/json

{
  "ui_mode": "dark",
  "timezone": "Asia/Tokyo"
}

### Publish draft questionnaire
PATCH {{baseUrl}}/v1/users/{{seedUserId}}/questionnaires/{{draftQuestionnaireId}}/status
Content-Type: application/json

{
  "status": "published"
}
